version: '3'

networks:
  laravel:
    driver: bridge

services:
  nginx:
    image: nginx
    container_name: nginx_user
    depends_on:
      - user
      - mysql
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8030:80"
    networks:
      - laravel

  mysql:
    image: mysql
    container_name: mysql_user
    restart: unless-stopped
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_ROOT_PASSWORD: example
      MYSQL_PASSWORD: example
    networks:
      - laravel

  user:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel


